parameters:
        BUFFER_SIZE : 100000     # replay buffer size.
        BATCH_SIZE : 256         # minibatch size
        GAMMA : 0.99             # discount factor
        TAU : 0.01               # for soft update of target parameters
        ACTOR_LR : 0.001         # learning rate for Actor network
        ACTOR_HIDDEN_1: 128      # Number of features of hidden layer 1 of Actor NN
        ACTOR_HIDDEN_2: 64       # Number of features of hidden layer 2 of Actor NN
        CRITIC_LR : 0.001        # learning rate for Critic network
        CRITIC_OBS_HIDDEN_1: 128 # Number of features of hidden layer 1 of Critic NN (observation branch)
        CRITIC_ACT_HIDDEN_1: 64  # Number of features of hidden layer 1 of Critic NN (actions branch)
        CRITIC_HIDDEN_2: 64      # Number of features of hidden layer 2 of Critic NN (common branch)
        CRITIC_HIDDEN_3: 32      # Number of features of hidden layer 3 of Critic NN (common branch)
        SIGMA: 0.01              # noise generator sigma parameter
        THETA: 0.15              # noise generator theta parameter        
        UPDATE_EVERY : 10        # how often to update the network
        K : 16                   # times to train each update
        OUT_SCALE : 1.0          # scale of actions domain. In this case actions are [-1,1]

